language: node_js
sudo: false
node_js: - "stable"

addons:
  artifacts:
    paths:
    - ./coverage/lcov-report
    - ./coverage/jest-result.txt

before_install:
- npm update

install:
- npm install

script: 
- npm run test:coverage

after_script:
- npm run test:coveralls